### ISSUE TITLE
Store track data on the app and update it when complete data from server are available

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-app#14]
A seamless UX requires the app to store temporary tracks data on the app, to make them available to the user within the list/detail activities (see #13) even before the track has been processed server side.

The usual approach to deal with this (re-conciliation patterns) consists into 

1. saving track data already available on the app side (e.g. geometry and datetimes)
2. send the track to the server, which will process it and do the calculations
3. the server notifies the app about updated data and the app merges data from the server with local data

A simplified approach can show the user not yet processed tracks with a placeholder saying "track data not available yet". Anyway the app must keeps track of these tracks...

**Comment by offtherailz** [comment]
Just to take note: 
I see an history in this PR https://github.com/geosolutions-it/smb-portal/pull/137 
Different segments can be shown in a list like this.
https://stackoverflow.com/questions/44936373/how-to-create-android-timeline-view-like-google-location-history
