### ISSUE TITLE
Badges (levels) view

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-app#16]
A view in the (yet to be created) profile page to show the [badges gained by a user](https://github.com/geosolutions-it/smb-backend/issues/11):

[The icons to bu used are those by Autorivari](https://drive.google.com/open?id=0B1Wv7RxKtPunUUlLMmFva1REamFndVZhTmdzLXhTN29BRGJJ)

I would organize them in a grid, with levels for the same badge on the same row. Something like this, but using the official icons:

![image](https://user-images.githubusercontent.com/571129/45223521-c6457480-b2b7-11e8-91fe-742ad8c151d1.png)

**Comment by offtherailz** [comment]
There are some different description for each badge to show if a target has been achieved or not.
I suggest something like this: 
[image](https://user-images.githubusercontent.com/1279510/45755224-23c5b380-bc1e-11e8-87a6-a645020c07d4.png)

**Comment by offtherailz** [comment]
Yes, the "descriptions" are: 
"Before" --> to Achieve 
"After"  --> Achieved 
using the naming used in this issue: https://github.com/geosolutions-it/smb-backend/issues/11

About the icons, yes, the mockup was old.

**Comment by giohappy** [comment]
Obviously use the [italian descriptions](https://docs.google.com/document/d/1_Crk--vzG5Qn-aIa9OZgsvP6aaE6d26PIwaKsZmrCv0) (if i18n is not configured for the app yet)
