### ISSUE TITLE
switch S3 storage to different bucket names

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/smb-app#34]
The following new buckets have been created and should now be used:

-  `geosolutions-it-smb-test`
-  `geosolutions-it-smb-production`

These are already configured to send the appropriate notification whenever new data is created. The notification is sent to a relevant SNS topic that has the correct lambda(s) subscribed to it

S3 bucket name | SNS topic that is notified | ARN of lambda that is subscribed to SNS topic
---------------------|---------------------------------|-----------------------------------------------------------
geosolutions-it-smb-test | smb_backend_dev | arn:aws:lambda:us-west-2:227022658256:function:savemybike-smbbackend:$LATEST
geosolutions-it-smb-production | smb_backend_production | arn:aws:lambda:us-west-2:227022658256:function:savemybike-smbbackend:production

The lambda that is ultimately listening for the S3 notifications is the current one, that performs track ingestion and calculations for badges and prizes

**Comment by Gnafu** [comment]
Buckets names are only present in

API Gateway --> /upload and /upload-dev --> /{folder} resource --> PUT Integration Request --> path override: <bucket_name>/<additional_path>/{iamsub}/{object} 

When changing it, ensure to use a role with the correct access permissions.

**Comment by giohappy** [comment]
@ricardogsilva paths have been renamed and the API republished.
Let's do some tests.
