### ISSUE TITLE
Change session upload workflow and UI

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/smb-app#70]
Sessions: after the session list has been flushed (to the server) the list should be substituted by a message like "Le tue registrazione sono state prese in carico dal sistema. A breve le potrai vedere nella lista delle tracce. Assicurati di aggiornare la lista, trascinandola in basso col dito, per ricevere le nuove tracce elaborate"

To confirm duplicated, see #65

**Comment by offtherailz** [comment]
@giohappy can you confirm?

**Comment by giohappy** [comment]
I think this is complementary to the other. This message should be visible when no sessions are in the list (they've been already completely flushed to the server). #65 should mark sesssions as in uploading state during the upload.
